// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eszsdrpvdjypensopndk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzenNkcnB2ZGp5cGVuc29wbmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MTEzMjAsImV4cCI6MjA2NDk4NzMyMH0.hToK17rZcufiEibQJJZ8CJrvIGmIYAgd-_Yf9Ov5HH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);